#!/usr/bin/python3

class MultiplicationTable:
        def __init__(self, n):
            self.n = n
        def generate_table(self):
            for i in range(1, self.n+1):
                for j in range(1, self.n+1):
                    print("{:3d}".format(i*j), end=" ")

                print()


table = MultiplicationTable(12)
table.generate_table()
                                                                                    
